### ISSUE TITLE
openrtb2 native request field should be omitempty

### ISSUE THREAD

**Issue by gokhanm** [prebid/openrtb#12]
Some RTB exchanges are waiting for openrtb 2.6 native request with empty native object.

```go
type Native struct {
	Request string `json:"request"`
	Ver string `json:"ver,omitempty"`
        ....
```

When I marshal the rtb.BidRequest object to json, the json looks like this and exchange returns bad request response.
```go
    "imp": [
        {
            "id": "ee8e0c40",
            "native": {
                "request": ""
            },
            "tagid": "2123eqweqw"
        }
    ],
```

but rtb exchange is waiting like this

```
    "imp": [
        {
            "id": "ee8e0c40",
            "native": {},
            "tagid": "2123eqweqw"
        }
    ],
```

**Comment by bsardo** [comment]
Hi @gokhanm,
Thanks for raising this point, however, Prebid Server adheres to the IAB OpenRTB standards which indicate that `imp.native.request` is required (https://github.com/InteractiveAdvertisingBureau/openrtb2.x/blob/main/2.6.md#329---object-native-).
This is why the `request` field does not have an `omitempty` tag which results in a native object containing `"request": ""` in the scenario you described.
I hope this helps.
