### ISSUE TITLE
require github.com/prebid/openrtb/v17: version "v18.0.0" invalid: should be v17, not v18

### ISSUE THREAD

**Issue by andot** [prebid/openrtb#5]
github.com/prebid/openrtb/v17 need change to github.com/prebid/openrtb/v18.

**Comment by spanwp** [comment]
I agree. Now it is impossible to use v18 correctly.

**Comment by SyntaxNode** [comment]
Ugh. I forgot to change the module version on the last release. Thanks for bringing this to my attention. I'll fix it ASAP.

**Comment by andot** [comment]
Need a new tag such as v18.0.1

**Comment by SyntaxNode** [comment]
New tag created. I waited to merge in a second PR to add a formal retraction of v18.0.0.
